// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaj9Soau38FXSa_UR-F2PJlBIvuwGckfM',
    appId: '1:331873383917:web:7ab5079d252bac2c81e3e4',
    messagingSenderId: '331873383917',
    projectId: 'project-dispesas-eafr',
    authDomain: 'project-dispesas-eafr.firebaseapp.com',
    storageBucket: 'project-dispesas-eafr.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlOUjniul2D3pvlM8PxjEhro5cRY6RlHo',
    appId: '1:331873383917:android:38e076e9b3e0404881e3e4',
    messagingSenderId: '331873383917',
    projectId: 'project-dispesas-eafr',
    storageBucket: 'project-dispesas-eafr.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2k4RcJAda4ut2Uxlrxrx_iT5L219G9kU',
    appId: '1:331873383917:ios:d7926b08a3304e0a81e3e4',
    messagingSenderId: '331873383917',
    projectId: 'project-dispesas-eafr',
    storageBucket: 'project-dispesas-eafr.appspot.com',
    iosClientId: '331873383917-i57ar9aaa7hn4hl4igok4ihsp1ib0gcv.apps.googleusercontent.com',
    iosBundleId: 'com.example.appDispesas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2k4RcJAda4ut2Uxlrxrx_iT5L219G9kU',
    appId: '1:331873383917:ios:d7926b08a3304e0a81e3e4',
    messagingSenderId: '331873383917',
    projectId: 'project-dispesas-eafr',
    storageBucket: 'project-dispesas-eafr.appspot.com',
    iosClientId: '331873383917-i57ar9aaa7hn4hl4igok4ihsp1ib0gcv.apps.googleusercontent.com',
    iosBundleId: 'com.example.appDispesas',
  );
}
